import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";


export const metadata: Metadata = {
  title: "Portifólio",
  description: "Generated by Renan Carletti",

  

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br"
    suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
